services:
  mugi-idp-db:
    image: postgres:14-alpine
    container_name: mugi-idp-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mugi_idp